### PR TITLE
Makes the order of events in init clearer in the log

### PR DESCRIPTION
**Pull request by Grendel-Grendel-Grendel**
This is a tiny PR that adds some messages indicating when termrc and cpurc are started by the init process. This makes the order of events in the init process more clear to everyone.

### CODE REVIEW

**Comment by bldybuild** [comment]
Commit 22aca942089d64bea02439b3bd80fbff766c31eb is not signed-off.

Please fix these issues:

>	1. yuy168 has not signed-off 22aca94.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by bldybuild** [comment]
Commit 405ea674765db09beb593a94763df94a53f26103 is not signed-off.

Please fix these issues:

>	1. Grendel-Grendel-Grendel has not signed-off 405ea67.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by gmacd** [comment]
I'm fine with it

**Comment by bldybuild** [comment]
Commit 2730ecdffba4ca1e1da0640033939c7322543545 is not signed-off.

Please fix these issues:

>	1. Grendel-Grendel-Grendel has not signed-off 2730ecd.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Pull request merged**
