### PR TITLE
This is the acpi code. I'm changing how it works -- no notes sent to the program, it just reads from acpiintr.

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by elbing** [comment]
wow, let me test it. It looks better now.

**Comment by elbing** [comment]
Terminal didn't work, because (with GO9PTERM script) it didn't find a ps2 mouseport.
Also realemu misses dev/realmode and vga seems weird:

```
init: starting /bin/rc
10.0.2.15 Feb 12 21:13:11 starting dns resolver on 10.0.2.15's /net
#P/ps2mouse: '#P/ps2mouse' file does not existaux/realemu: open realmodemem: '#P/realmodemem' file does not exist
mkvbe: '/dev/realmode' bad arg in system call
aux/vga: controller not in /lib/vgadb, not vesa
0xC0000 55 AA 4C E9 44 56 6D 00 00 00 00 00 00 00 00 00  U.L.DVm.........
0xC0010 00 00 00 00 00 00 00 00 D8 8E 00 00 00 00 49 42  ..............IB
0xC0020 4D 00 66 55 66 89 E5 66 53 84 C0 74 2C 66 BB 00  M.fUf..fS..t,f..
0xC0030 40 00 00 FE C8 74 38 66 0F B7 D2 66 0F B7 C9 66  @....t8f...f...f
0xC0040 0F AF D1 66 C1 FA 03 66 89 D3 9C 66 81 C3 FF 1F  ...f...f...f....
0xC0050 00 00 9D 81 E3 00 E0 EB 16 66 D1 E1 0F AF D1 66  .........f.....f
0xC0060 89 D3 9C 66 81 C3 FF 07 00 00 9D 81 E3 00 F8 66  ...f...........f
0xC0070 89 D8 66 5B 66 5D C2 02 00 66 55 66 89 E5 66 56  ..f[f]...fUf..fV
0xC0080 66 53 67 66 8B 5D 08 66 89 DE 67 8A 5D 0C 66 C1  fSgf.].f..g.].f.
0xC0090 E0 10 66 0F B7 D2 66 09 C2 66 31 C0 8E C0 26 66  ..f...f..f1...&f
0xC00A0 89 16 0C 01 66 89 F0 3C 01 74 13 72 13 3C 03 0F  ....f..<.t.r.<..
0xC00B0 94 C3 66 4B 66 83 E3 EE 66 83 C3 2B EB 02 B3 0E  ..fKf...f..+....
0xC00C0 66 BA 40 00 00 00 8E C2 66 4B 26 88 1E 84 00 8E  f.@.....fK&.....
0xC00D0 C2 66 0F B6 C9 26 89 0E 85 00 66 5B 66 5E 66 5D  .f...&....f[f^f]
0xC00E0 C2 02 00 66 55 66 89 E5 66 57 66 56 66 53 66 53  ...fUf..fWfVfSfS
0xC00F0 66 89 D3 67 66 89 4D F0 66 89 C2 66 39 D9 73 1A  f..gf.M.f..f9.s.
aux/vga: vgactlw: <type vga>: bad VGA control message "type vga"
```
But it ended giving me a console prompt.
GO9PCPU worked like a charm.

**Comment by rminnich** [comment]
Yeah, I'm still not that comfortable with this code. It made a few too many changes for me. That said, I really don't see how it could have affected the things you're seeing. If you go back to master and recompile with the same toolchain and make the same test you're sure it still works?

**Comment by rminnich** [comment]
Closing this. The lesson here is you don't make such wide-ranging changes. I am breaking it down into a smaller set of changes so we can find out where it's broken.

**Pull request closed without merging**
