### PR TITLE
Remove non-standard Ken C pragmas.

### PR DESCRIPTION
**Pull request by rminnich**
clang doesn't like them.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
Boots fine in qemu.

**Comment by elbing** [comment]
Tired of seeing them? Ok for me. In fact this could allow us to remove pragmas warning in cflags. When it passed travis, get in.

**Comment by rminnich** [comment]
can you LGTM. I don't want to self-approve.

**Comment by rminnich** [comment]
woo hoo! travis finally passed.

**Comment by elbing** [comment]
LGTM

**Comment by rminnich** [comment]
Another bunch of legacy junk bites the dust.

**Pull request merged**
