### PR TITLE
get rid of imap4d

### PR DESCRIPTION
**Pull request by rminnich**
We may someday have a MTA but it's not likely to be this old piece of cruft.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by elbing** [comment]
LGTM

**Comment by sevki** [comment]
@rminnich needs to be updated

**Comment by grd** [comment]
This CR is probably corrupting #87 since I also removed imap4d. Shall I remove that commit first?

**Comment by elbing** [comment]
Yes, please remove all of imap4d from 87 and apply Ron's suggestions. Then we could merge 87 too.

**Comment by grd** [comment]
I have applied Ron's suggestions (unless I have missed something). I don't have access to git right now but consider it done in a couple of hours.

**Comment by elbing** [comment]
Great! thanks

**Comment by rminnich** [comment]
so do I remove this CL or merge it or ...

**Comment by grd** [comment]
They are now detached so it can be merged.

**Pull request merged**
