### PR TITLE
Fix for panic in Mahjongg #88

### PR DESCRIPTION
**Pull request by keedon**
It looks like a bad interaction between the malloc pool and the image pool
when allocating images.  I've removed the image pool& it works.

Can someone check this out - it works, but I'm a bit twitchy I've missed
something. c.f. memimagemove

### CODE REVIEW

**Comment by elbing** [comment]
I'm not sure, specially of replacing poolalloc for malloc. Poolalloc must be fixed if it's wrong, but it's a good work. Qmalloc was fixed months ago, we should have it always aligned with libc/port/malloc.c if we change anything in it. Anyway, pool mess in qmalloc kernel was included when I brought back screen and vga in September. Originally wasn't there. Surely my mistake, but for an arcane reason I can't remember, I found some undefined things that required including pool mess in it (I remember a talk with Ron about this) that originally was in old alloc.c. I'm not sure if it was due to some sources now removed or changed. So removing it now couldn't be wrong at all, now it seems as it was before September 2nd.

Look at: [Original qmalloc.c](https://github.com/Harvey-OS/harvey/commit/da1fc778d8ec321fb85a6c044bfbc0ac0bc81ef7)

**Comment by rminnich** [comment]
SGTM

**Comment by rminnich** [comment]
If this works for you go for it.

**Comment by elbing** [comment]
LGTM

**Pull request merged**
