### PR TITLE
Skeleton aarch64 files: minimum needed to build most libraries.

### PR DESCRIPTION
**Pull request by dancrossnyc**
Add the very minimum files needed to build most Harvey libraries:
these are just placeholders.

Signed-off-by: Dan Cross <cross@gajendra.net>

### CODE REVIEW

**Comment by elbing** [comment]
Do you want to add things or just merging the skeleton? ok for me both.

**Comment by dancrossnyc** [comment]
Just putting in the skeleton for right now; I'll start hanging meat off of it in the next commits.

**Comment by elbing** [comment]
Ok, go for it.

LGTM

[Approved with PullApprove](https://pullapprove.com/Harvey-OS/harvey/pull-request/230/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Harvey-OS/harvey)

**Comment by elbing** [comment]
LGTM (annoying)

**Pull request merged**
