### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by ericfode**

### CODE REVIEW

**Comment by bldybuild** [comment]
Commit a2a0b1875776e792bece991f31ca54001dd5757a is not signed-off.

Please fix these issues:

>	1. Eric Fode has not signed-off a2a0b18.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by ericfode** [comment]
I think I signed it off by amending, but it does not seem to be showing up...

**Comment by elbing** [comment]
```
git commit -s --amend; git push -f yourgithubname yourbranchname
```
after the -s --amend you just need to exit nano/vim writing the changes and then push them to the PR.

**Comment by elbing** [comment]
Included in #801 Thanks!

**Pull request closed without merging**
