### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by sevki**
Signed-off-by: Sevki <s@sevki.org>

### CODE REVIEW

**Comment by elbing** [comment]
Seems travis hasn't available a calng 4.0 package.
For 3.9 it's needed the clang-3.9.json file like with older versions.

**Comment by rminnich** [comment]
is this one going to die or get fixed?

**Comment by sevki** [comment]
I'll get it fixed sorry.

**Comment by rminnich** [comment]
we need to fix or close this.

**Comment by driusan** [comment]
@elbing are you sure it's not just a typo? The other versions are `3.x`, while the `4.0` is `4-0` in the diff.

**Comment by bldybuild** [comment]
Commit b07851706da944e1a97bea9639453d9134c6a1a5 is not signed-off.

Please fix these issues:

>	1. Sevki has not signed-off b078517.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by elbing** [comment]
Shit, rebase this, please.

**Pull request merged**
