### PR TITLE
Removed unused funcs in libsec

### PR DESCRIPTION
**Pull request by grd**

### CODE REVIEW

**Comment by grd** [comment]
I put the hot potatoes in a separate CR. This way it's better manageable.

**Comment by elbing** [comment]
Ok for me, Ron?. Most of these seems like attempts to implementing something or failed projects. In fact this is temporary, but "temporary" is a word very lazy in Harvey, so a bit cleaning to have -Werror in core building is good. You now for me entire libsec must be gone. We'll back over this when there would be more time or someone can do it for us.

**Comment by elbing** [comment]
LGTM.

**Comment by rminnich** [comment]
needs rebase.

**Comment by rminnich** [comment]
See how it says 'this branch is out of date'. You need to click the update button.

**Comment by rminnich** [comment]
out of date since I merged the other one, sorry.

**Pull request merged**
