### PR TITLE
fix troff fonts

### PR DESCRIPTION
**Pull request by floren**
Send fixcase to hell.

Signed-off-by: John Floren <john@jfloren.net>

### CODE REVIEW

**Comment by gmacd** [comment]
A bit late, but looks like this PR causes problems on Mac, where the filesystem is case insensitive by default.  Now, if I clone a fresh repo on my mac, it thinks the HB, HI and HX files have been modified.

This is going to be quite off-putting to anyone trying to develop on a mac.

**Comment by elbing** [comment]
Add them to .gitignore.

**Comment by gmacd** [comment]
At first attempt, that doesn't work.

**Comment by rminnich** [comment]
we made a decision a while back to not work on case-insensitive file systems. Is there any way to remove or change the conflicting names so they work on case-insensitive file systems without needing fixcase? I have no idea.

**Pull request merged**
