### PR TITLE
symlink support, step 1: constants.

### PR DESCRIPTION
**Pull request by rminnich**
And so it begins.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by elbing** [comment]
Well, here then. Pandora's box opened. for curiosity, how do you know the value of that constants?

**Comment by elbing** [comment]
LGTM.

**Comment by elbing** [comment]
Updating branch needed.

**Comment by rminnich** [comment]
We get to set the constants, so I made some up

LGTM

**Pull request merged**
