### PR TITLE
BUILD files

### LINKED ISSUE #47: Need to install new BUILD files
As part of the move to the new BUILD system we need to install the BUILD files in the right place.

### PR DESCRIPTION
**Pull request by sevki**
to test

	go get -u sevki.org/build/cmd/build
	git clone git@github.com:sevki/harvey.git harvey-sevki
	cd harvey-sevki
	build //.:kernel
	qemu-system-x86_64 --kernel build_out/amd64/harvey -no-reboot -m 512 

closes #47 
```
[ OK ] //sys/src/libc:syscallheader
[ OK ] //sys/src/9/amd64:error
[ OK ] //sys/src/libc:9syscall
[ OK ] //sys/src/9/amd64:errstr
[ OK ] //sys/src/9/amd64:systab
[ OK ] //sys/src/libmemlayer:libkmemlayer
[ OK ] //sys/src/libbio:libbio
[ OK ] //sys/src/libdraw:libkdraw
[ OK ] //sys/src/9/amd64:sys
[ OK ] //sys/src/libsec:libksec
[ OK ] //sys/src/libmemdraw:libkmemdraw
[ OK ] //sys/src/libip:libkip
[ OK ] //sys/src/libauthsrv:libauthsrv
[ OK ] //sys/src/libmemdraw:libmemdrawiprint
[ OK ] //sys/src/libsec:libsec
[ OK ] //sys/src/libthread:libthread
[ OK ] //sys/src/libmemlayer:libmemlayer
[ OK ] //sys/src/libc:libkc
[ OK ] //sys/src/libip:libip
[ OK ] //sys/src/libmp:libmp
[ OK ] //sys/src/libmemdraw:libmemdraw
[ OK ] //sys/src/liboventi:liboventi
[ OK ] //sys/src/libflate:libflate
[ OK ] //sys/src/lib9p:lib9p
[ OK ] //sys/src/libhttpd:libhttpd
[ OK ] //sys/src/liblex:liblex
[ OK ] //sys/src/libstdio:libstdio
[ OK ] //sys/src/libString:libString
[ OK ] //sys/src/libndb:libndb
[ OK ] //sys/src/libauth:libauth
[ OK ] //sys/src/libframe:libframe
[ OK ] //sys/src/libplumb:libplumb
[ OK ] //sys/src/libcontrol:libcontrol
[ OK ] //sys/src/libgeometry:libgeometry
[ OK ] //sys/src/libbin:libbin
[ OK ] //sys/src/libventi:libventi
[ OK ] //sys/src/libmach:libmach
[ OK ] //sys/src/libavl:libavl
[ OK ] //sys/src/libdisk:libdisk
[ OK ] //sys/src/libregexp:libregexp
[ OK ] //sys/src/libcomplete:libcomplete
[ OK ] //sys/src/libdraw:libdraw
[ OK ] //sys/src/cmd/usb/usbd:devtab
[ OK ] //sys/src/9/boot:bootamd64cpuc
[ OK ] //sys/src/cmd/disk/prep:calc
[ OK ] //sys/src/cmd/rc:syn
[ OK ] //sys/src/libusb:libusb
[ OK ] //sys/src/cmd/venti/srv:libvs
[ OK ] //sys/src/9/boot:libboot
[ OK ] //sys/src/libc:libc
[ OK ] //sys/src/cmd:date
[ OK ] //sys/src/cmd/disk/prep:fdisk
[ OK ] //sys/src/cmd/ip/ipconfig:ipconfig
[ OK ] //sys/src/cmd:ed
[ OK ] //sys/src/cmd/usb/usbd:usbd
[ OK ] //sys/src/cmd/fossil:fossil
[ OK ] //sys/src/cmd:cat
[ OK ] //sys/src/cmd/acme:acme
[ OK ] //sys/src/cmd/auth/factotum:factotum
[ OK ] //sys/src/cmd/aux/realemu:realemu
[ OK ] //sys/src/cmd:srv
[ OK ] //sys/src/cmd/venti/srv:venti
[ OK ] //sys/src/9/amd64:init
[ OK ] //sys/src/cmd:bind
[ OK ] //sys/src/cmd:ls
[ OK ] //sys/src/cmd:mount
[ OK ] //sys/src/cmd:ps
[ OK ] //sys/src/9/boot:bootamd64cpu
[ OK ] //sys/src/cmd:echo
[ OK ] //sys/src/cmd/disk/prep:prep
[ OK ] //sys/src/cmd/rc:rc
[ OK ] //sys/src/cmd/aux/vga:vga
[ OK ] //sys/src/cmd:ratrace
[ OK ] //sys/src/9/amd64:date
[ OK ] //sys/src/9/amd64:fdisk
[ OK ] //sys/src/9/amd64:ipconfig
[ OK ] //sys/src/9/amd64:ed
[ OK ] //sys/src/9/amd64:usbd
[ OK ] //sys/src/9/amd64:fossil
[ OK ] //sys/src/9/amd64:cat
[ OK ] //sys/src/9/amd64:factotum
[ OK ] //sys/src/cmd/aux/console:screenconsole
[ OK ] //sys/src/9/amd64:realemu
[ OK ] //sys/src/9/amd64:srv
[ OK ] //sys/src/9/amd64:venti
[ OK ] //sys/src/9/amd64:inith
[ OK ] //sys/src/9/amd64:bind
[ OK ] //sys/src/9/amd64:ls
[ OK ] //sys/src/9/amd64:mount
[ OK ] //sys/src/9/amd64:ps
[ OK ] //sys/src/9/amd64:boot
[ OK ] //sys/src/9/amd64:echo
[ OK ] //sys/src/9/amd64:prep
[ OK ] //sys/src/9/amd64:rc
[ OK ] //sys/src/9/amd64:vga
[ OK ] //sys/src/9/amd64:ratrace
[ OK ] //sys/src/9/amd64:screenconsole
[ OK ] //sys/src/9/amd64:amd64cpu
[ OK ] //sys/src/9/amd64:harvey
[ OK ] //.:harvey
[ OK ] //.:kernel
```

### CODE REVIEW

**Comment by elbing** [comment]
Conflicts?

**Comment by sevki** [comment]
@elbing working on it

**Comment by rminnich** [comment]
why not merge?

**Comment by sevki** [comment]
because the new build isn't working yet

**Comment by sevki** [comment]
-1
not ready

**Comment by sevki** [comment]
:-1: 
not ready

**Comment by sevki** [comment]
:-1:

**Comment by rminnich** [comment]
Immediately fails: sys/src/cmd/fossil/BUILD is missing. 

I once again urge you to just get these BUILD files installed into the tree so we can all start to help. But I don't say looks good unless you tell me to :-)

**Comment by rminnich** [comment]
Still no good. I do a 
hub pull https://github.com/Harvey-OS/harvey/pull/53
and it makes a nice branch and all, and it immediately fails on weird errors about interrupt, or it still looks for libsunrpc stuff. This is really not working well.

**Comment by sevki** [comment]
yeah, this is supposed to fail with the new build tool. that's why I -1'd it. Please do not review this yet.

**Comment by elbing** [comment]
Update you master, sevki, or it will be worse later. We havee committed
anything new, so take the chance.

Álvaro

**Comment by rminnich** [comment]
LGTM

This meets the minimum requirement: it does not break the old build tool. I just did a full build and boot cycle with the old tool and it all works. Now we can help get the new tool working.

THere are still problems. This can't build riscv. There are amd64 specific settings in sys/src/FLAGS. But we need to get going on this so we'll commit it and fix it.

**Pull request merged**
