### PR TITLE
apex: add a program to test how apex exits

### PR DESCRIPTION
**Pull request by rminnich**
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
not needed, so we can delete this if we don't want it.

**Comment by elbing** [comment]
Not sure... When would be an installation iso or anything like that, toolchain, Go and APEX will be in it by default, with the possibility of being updated through git. But for now, that we must mount the system by pieces... As you wish.
Needs a rebase, anyway.

**Comment by elbing** [comment]
Thought better, if it's not needed, delete it.

**Comment by rminnich** [comment]
not needed -- it was a simple apex bug and this doesn't really test anything interesting.

**Pull request closed without merging**
