### PR TITLE
Bring in the virtqueue definitions from the virtio spec 1.0. Make sure BAR address and size are picked up for virtio-pci devices with ID=0x00 (e. g. virtio-9p).

### PR DESCRIPTION
**Pull request by dmgolubovsky**
Next small step in the virtio adoption. The virtqueue definitions brought in from the virtio spec 1.0 site. The virtio_ring.h file has been #include'd into devpci.h just to make sure it compiles for now. It has been noticed that the when the PCI devices are scanned, devices with ID=0x00 are skipped, so pci(8) does not display BARs and sizes for them. Devices like virtio-9p belong to this category, so now their information is displayed more accurately.

Before this change (pci(8) output from the previous pull request):

0.0.0:  brg   06.00.00 8086/1237   0
0.1.0:  brg   06.01.00 8086/7000   0
0.1.1:  disk  01.01.80 8086/7010   0 4:0000c2a1 16
0.1.3:  brg   06.80.00 8086/7113   9
**0.10.0: virtio-balloon 00.ff.00 1af4/1002  10**
0.11.0: virtio-disk    01.00.00 1af4/1001  11 0:0000c1c1 64 1:fc098000 4096
0.2.0:  vid   03.00.00 1b36/0100  10 0:f4000000 67108864 1:f8000000 67108864 2:fc090000 8192 3:0000c201 32
0.3.0:  net   02.00.00 10ec/8139  11 0:0000c001 256 1:fc092000 256
0.4.0:  virtio-net     02.00.00 1af4/1000  11 0:0000c221 32 1:fc093000 4096
**0.5.0:  virtio-9p      00.02.00 1af4/1009  10**
0.6.0:  virtio-console 07.80.00 1af4/1003  10 0:0000c241 32 1:fc095000 4096
0.7.0:  virtio-scsi    01.00.00 1af4/1004  11 0:0000c141 64 1:fc096000 4096
0.8.0:  virtio-disk    01.00.00 1af4/1001  11 0:0000c181 64 1:fc097000 4096
**0.9.0:  virtio-rng     00.ff.00 1af4/1005  10**

After the change:

0.0.0:  brg   06.00.00 8086/1237   0
0.1.0:  brg   06.01.00 8086/7000   0
0.1.1:  disk  01.01.80 8086/7010   0 4:0000c2a1 16
0.1.3:  brg   06.80.00 8086/7113   9
**0.10.0: virtio-balloon 00.ff.00 1af4/1002  10 0:0000c281 32**
0.11.0: virtio-disk    01.00.00 1af4/1001  11 0:0000c1c1 64 1:fc098000 4096
0.2.0:  vid   03.00.00 1b36/0100  10 0:f4000000 67108864 1:f8000000 67108864 2:fc090000 8192 3:0000c201 32
0.3.0:  net   02.00.00 10ec/8139  11 0:0000c001 256 1:fc092000 256
0.4.0:  virtio-net     02.00.00 1af4/1000  11 0:0000c221 32 1:fc093000 4096
**0.5.0:  virtio-9p      00.02.00 1af4/1009  10 0:0000c101 64 1:fc094000 4096**
0.6.0:  virtio-console 07.80.00 1af4/1003  10 0:0000c241 32 1:fc095000 4096
0.7.0:  virtio-scsi    01.00.00 1af4/1004  11 0:0000c141 64 1:fc096000 4096
0.8.0:  virtio-disk    01.00.00 1af4/1001  11 0:0000c181 64 1:fc097000 4096
**0.9.0:  virtio-rng     00.ff.00 1af4/1005  10 0:0000c261 32**

Next steps in this direction probably should be picking up the capability and virtqueue structures when scanning the PCI bus, and make devpci display them as subdirectories and files. But this involves massive coding and will take time. This patch is simple and may be applied now.

Thanks.

### CODE REVIEW

**Comment by elbing** [comment]
LGTM

**Comment by elbing** [comment]
Please, push "update branch" button.

**Comment by rminnich** [comment]
hey, please push update and we can merge this. It's wonderful to have it.

**Comment by dmgolubovsky** [comment]
Updated.

Thanks for reviewing.

**Comment by elbing** [comment]
You're welcome, we need kernel hackers more than eating.

**Pull request merged**
