### PR TITLE
Igfx

### PR DESCRIPTION
**Pull request by rminnich**
This is pulling commits from harvey to include the vgaigfx device, stopping right before

commit 4f85115526a87063489dc7cf347343bd520159b1
Author: cinap_lenrek <cinap_lenrek@felloff.net>
Date:   Sun Sep 13 20:33:17 2020 +0200

    kernel: massive pci code rewrite

We can do that next. It's big. This needs testing.

### CODE REVIEW

**Comment by rminnich** [comment]
do NOT squash commits!

**Comment by floren** [comment]
Ron, the signoff checker is complaining.

Have you compiled this? Does it boot?

**Comment by rminnich** [comment]
oh hell no, have not compiled it.
have not booted it.
don't really have a good place to test.

**Comment by floren** [comment]
I'll try to test this on my thinkpad over the weekend.

**Comment by rminnich** [comment]
does not build at home, which makes me wonder if our CI test is bogus.

**Review by dancrossnyc — APPROVED** [review]

**Comment by dancrossnyc** [comment]
Needs a DCO sign-off for the import. We should be able to provide a proxy for that.

**Comment by floren** [comment]
Don't merge this yet. The PR identifies the commits we need, but last time I checked they do not actually compile in our kernel. Some adjustments are required due to a decade's worth of drift between codebases :)

**Review by floren — CHANGES_REQUESTED** [review]
Needs work to actually compile.

**Comment by rminnich** [comment]
well maybe someone else would like to try it :-)

**Pull request closed without merging**
