### PR TITLE
Small grammar fix

### PR DESCRIPTION
**Pull request by voronoipotato**
Fix this by change one of them.
to
Fix this by changing one of them.

### CODE REVIEW

**Comment by bldybuild** [comment]
Commit 0b64db586c7cf7064ecff1e844f3905907c4a8dc is not signed-off.

Please fix these issues:

>	1. Alan Ball has not signed-off 0b64db5.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by elbing** [comment]
The sign has to be in the commit message. After some issues we cannot afford an unsigned commit.
The easier way is `git commit -s --amend` in your local and the a `git push -f` to your branch so it will get it. Thanks!

**Comment by voronoipotato** [comment]
I just did this through github, so uh I'm going to have to wait till I get home before I can do this.

**Comment by voronoipotato** [comment]
Amusingly I actually know of the conflict you're speaking about since they made a big fuss on it about lobsters. No disrespect intended for any of the parties involved. I understand different people have different reasons for contributing.

**Comment by voronoipotato** [comment]
fatal: cannot create directory at '386/bin/aux': Invalid argument

huh weird.

**Comment by elbing** [comment]
ARCH=amd64

**Comment by sevki** [comment]
you can sign-off by appending `Signed-off-by: Your Name <Your.Name@example.com>` to the end of your commit message like so
image

We are well aware that this is a bit of a pain, but we do need to dot the i's and cross the t's. 
sorry for the inconvenience and thank you for your contribution :slightly_smiling_face:

**Comment by voronoipotato** [comment]
I'm not even trying to build I can't even like clone the repo. very strange.

**Comment by voronoipotato** [comment]
This commit isn't copyrighted anyway as it doesn't represent a meaningful change. Feel free to close this pull request and make the change yourself. The commit is signed with my github account anyway. 

Signed-off-by: Alan Ball <vash.arclan@gmail.com>

**Pull request closed without merging**
