### PR TITLE
Adding needed flags for OpenBSD egcc

### PR DESCRIPTION
**Pull request by elbing**

### CODE REVIEW

**Comment by elbing** [comment]
Probably clang needs the same por OpenBSD.

**Comment by raylai** [comment]
clang is not in /usr/bin on OpenBSD, can the paths be removed and just the binary names used?

**Comment by elbing** [comment]
It needs -nopie in final kernel linking line. But it doesn't boot.
I think without a newer binutils package it won't work on OpenBSD, too odd versions compiler<->binutils.

**Comment by rminnich** [comment]
six weeks is long enough, let's let this one go.

**Pull request closed without merging**
