### PR TITLE
Make intel 0x506e0 boot

### PR DESCRIPTION
**Pull request by gmacd**
No longer hangs when trying to work out the clock multiplier

Signed-off-by: Graham MacDonald <grahamamacdonald@gmail.com>

### CODE REVIEW

**Comment by gmacd** [comment]
I'd be all for it. This one caught me out when I was judiciously adding print statements.

**Comment by sevki** [comment]
@gmacd are we merging this?

**Comment by gmacd** [comment]
Didn't realise it had been approved

**Comment by sevki** [comment]
you're always pre-approved to me mate :smile:

**Pull request merged**
