### PR TITLE
grammar fix on a string

### PR DESCRIPTION
**Pull request by raMASTER**

### CODE REVIEW

**Comment by sevki** [comment]
Hey @raMASTER looks like you've just changed this on github and it looks like a really simple edit, but we have a pullapprove rule that requires that all commits should be Signed-off-by, do you mind ammending your commit and force pushing it?

```
git clone git@github.com:raMASTER/harvey.git
git commit --amend -s --no-edit
git push origin master -f
```
thanks.

**Comment by elbing** [comment]
Replica won't be used anymore, this remind us we should remove it (it should have been gone months ago). Harvey is not compatible with Plan 9 sources nor its binary format.

All Pull Request must be signed-off, we updated the contribution guide for this:
https://github.com/Harvey-OS/harvey/blob/master/CONTRIBUTING.md

Thanks!

**Comment by sevki** [comment]
@elbing can you open an issue for it?

**Comment by sevki** [comment]
ok opened an isse see #276

**Comment by sevki** [comment]
@raMASTER this is obsolete please see #276. 
Thanks for helping us find it.

**Pull request closed without merging**
