### PR TITLE
Keymaps are back

### PR DESCRIPTION
**Pull request by elbing**
Now I have an ES keyboard map :-)

Signed-off-by: Álvaro Jurado <elbingmiss@gmail.com>

### CODE REVIEW

**Comment by sevki** [comment]
why didn't you update bldy???????

**Comment by elbing** [comment]
Done.

**Comment by elbing** [comment]
what's wrong with sevki.io/dco "Waiting for status to be reported" forever?

**Comment by sevki** [comment]
your name with non-ascii chars are breaking the regex that looks for the signature `=?utf-8?q?=C3=81lvaro_Jurado?= <elbingmiss@gmail.com>`. I'll fix it today

**Pull request merged**
