### PR TITLE
revert console: building i8042.c (old kbdc)

### PR DESCRIPTION
**Pull request by elbing**
Hangs on boot (qemu rebooting loop)

Signed-off-by: Álvaro Jurado <elbingmiss@gmail.com>

### CODE REVIEW

**Comment by elbing** [comment]
Note: this only builds with bldy.

**Comment by rminnich** [comment]
This boots fine for me.
Are you building with clang or gcc. If clang, that's your problem.

**Comment by rminnich** [comment]
so does this hang or not?

**Comment by elbing** [comment]
No. It was due to clang.

**Comment by elbing** [comment]
I'll rebase later. It boots ok built with gcc. I'll test with latest Sevki's changes in bldy files.

**Comment by rminnich** [comment]
if you build with clang with old build does it work?

**Comment by rminnich** [comment]
builds and boots fine with old build and clang. I leave bldy for you.

**Pull request merged**
