### PR TITLE
bldy: demand that certain things have been built or fail

### PR DESCRIPTION
**Pull request by rminnich**
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by sevki** [comment]
bldy will fail if things are not built. why do we need this?

**Comment by rminnich** [comment]
because it's not building it, or at least not putting anything in amd64/bin/init. I don't know why. 

So we've been thinking bldy works all this time when it does not.

**Comment by rminnich** [comment]
Or at least I have. I went to set up bldy for riscv and suddenly realized it was not working for amd64 :-(

**Comment by sevki** [comment]
it definitely does build it. are you looking into `build_out/amd64/bin` or `amd64/bin`?

**Comment by sevki** [comment]
is this resolved?

**Pull request closed without merging**
