### PR TITLE
clang: add clang to the set of builders.

### PR DESCRIPTION
**Pull request by rminnich**
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
I can not BELIEVE that worked.

**Comment by rminnich** [comment]
-2

**Comment by elbing** [comment]
Ok for me. What a pity travis can't manage CC variable so easy.
+1

**Comment by rminnich** [comment]
in a forthcoming PR I am going to change the variable names.
HARVEYCC
HARVEYLD
etc.

**Pull request merged**
