### PR TITLE
Removed [-Wunused-function] warnings #14

### PR DESCRIPTION
**Pull request by grd**

### CODE REVIEW

**Comment by rminnich** [comment]
Overall: let's slow down here a bit. You want to be really careful. The noauth stuff in cpu should definitely stay, it's useful when you do a new port. But we don't do #if whatever type compilation in plan 9, and you really don't what that in there by default. You don't even want to make it easy to compile in: it's a security hole. But we've used it to effect on new ports. So how do we keep it and avoid the warnings? Just wrap the functions in #if 0 with appropriate warning? I'm fine with that. 

But the wholesale deletions bother me a bit.

Think hard before you approve this, everyone. Really, really hard.

**Comment by grd** [comment]
Oops. I only removed the dead code. I thought it would give some remarks but this is quite a lot. I agree, let's slow it down a bit.

**Comment by elbing** [comment]
Libsec for now it's needed, at least for drawterm and SSL v2 in kernel. Unless we improve dratwerm. For TLS in kernel too. Vendorizing libz was a first step for better crypto in Harvey, but now Rafa is working on ZFS, so this will have to wait.

**Comment by elbing** [comment]
Seems like hexdumps was a common exercise for debugging or univerity students...

**Comment by elbing** [comment]
Well, most of this is ok, just pay attention to Ron's comments for things tha can't be so in stats, prep and cpu. And all of that programs that will be replaced for better versions in go or posix in future (imapd, httpd, cifs...). Nice carnage :-).

**Comment by rminnich** [comment]
LGTM
it's better than it was but I don't like the cast of const char *s to char *. 

oh well. It's better.

**Comment by rminnich** [comment]
now it has conflicts.

**Comment by grd** [comment]
Sorry, I have to do this again.

**Pull request closed without merging**
