### PR TITLE
Fixed silly bug in devramfs - added test (/usr/harvey/bin/rc/ramdisk)

### PR DESCRIPTION
**Pull request by keedon**
Just leaving this here until we can have pull requests again.

Signed-off-by: keith.poole <keith.poole@gmail.com>

### CODE REVIEW

**Comment by gmacd** [comment]
A couple of random things:
 - What was the bug?  There's a lot of changes here, so hard to pinpoint the bug fix.
 - Maybe we should have a folder for test scripts rather than having them in a common folder (I need the same for UFS test scripts at some point)

**Comment by keedon** [comment]
the actual bug fix is line 140 "if(current->perm & QTDIR){" is now "if(current->perm & DMDIR){"

**Comment by elbing** [comment]
This can be gone isn't it?

**Comment by elbing** [comment]
done.

**Pull request closed without merging**
