### PR TITLE
ACPI changes to get us to a user-mode AML interpreter that can set IRQs.

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by elbing** [comment]
It boots, but I think you will want the output of kmesg. As you already know: Asus A1M1 realhw.

[out.txt](https://github.com/Harvey-OS/harvey/files/458004/out.txt)

If you think it's ok for now, let me know for an lgtm.

**Comment by elbing** [comment]
LGTM

**Comment by rminnich** [comment]
well, let's hope I did not just break a lot of things ...

**Comment by elbing** [comment]
Late, but you wanted to see it:

image

Real ASUS A1M1, just to have constancy about it.

**Pull request merged**
