### PR TITLE
tasunlock: add extra coherence (Richard Miller)

### PR DESCRIPTION
**Pull request by rminnich**
http://9legacy.org/9legacy/patch/9-taslock-unlock.diff

from 2016.

Signed-off-by: Ronald G Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
This does not fix the Go smp problem with locks. That said, it seems prudent.

**Comment by elbing** [comment]
What about iunlock() a few lines below? is not the same case?
```
l->m = nil;
l->key = 0;
coherence();
```
Maybe Richard didn't see it.

**Comment by rminnich** [comment]
nice catch, and I missed that. Hang on, I'll add it.

**Comment by rminnich** [comment]
Thanks for catching that!

This does not fix the Go program but it's nice to have.

**Comment by rminnich** [comment]
Richard did see it, I just missed it :-)

**Pull request merged**
