### PR TITLE
Changed qmalloc to use pool.c from libc

### PR DESCRIPTION
**Pull request by keedon**
Rationalised to simplify adding a slab allocator at a later time.

### CODE REVIEW

**Comment by elbing** [comment]
what shall we do... (popular song) with this?

**Comment by keedon** [comment]
No one seems keen, so I'll shelve it for now

**Comment by elbing** [comment]
@rminnich  usually says: "if it can be out of kernel, it must be out of kernel". I think you said it doesn't improve too much the system (faster), but if numbers are similars and it could be out... I vote for using pool from libc. Qmalloc (jmk work?) could be rescued later as a subproject or something, I think we talked about it months ago and someone said it was an unfinished work.
@rminnich, your wisdom, maybe I'm wrong.

**Comment by rminnich** [comment]
What's going on with this one. Just awaiting another tester?

**Comment by sevki** [comment]
I tried to carry this PR but as it turns out @keedon has deleted his fork and re-forked, hence there is no way this can get merged and is effectively obsolete, that's why I'm closing this. 

If anyone else wants to carry this, download and apply the patch @ https://patch-diff.githubusercontent.com/raw/Harvey-OS/harvey/pull/168.diff

**Pull request closed without merging**
