### PR TITLE
More warnings

### PR DESCRIPTION
**Pull request by grd**

### CODE REVIEW

**Comment by grd** [comment]
Yes, default:; looks weird but it didn't compile with default: alone.

**Comment by rminnich** [comment]
This needs to be revised. Just casting things that are const to non-const is asking for trouble. I realize fixing the declarations is painful but it's what we have to do.

**Comment by rminnich** [comment]
The convention then is 
default:
\tbreak;

**Comment by rminnich** [comment]
Yeah you're right I got mixed up with go again. But in any event the default:; is something I've not seen done. Just put a defaut:
break;

in there.

**Comment by grd** [comment]
Okay will do tomorrow.

**Comment by elbing** [comment]
Yes, you can remove acidleak.c and nm.c too. Old debugger has nothing to do now and nm is absolutely useless since we have binutils 2.26. Old nm can't read gcc objects.

**Comment by grd** [comment]
The mentioned files to be deleted will be another pull request.

**Comment by grd** [comment]
Next will be deleting unused functions [-Wunused-function]

**Comment by rminnich** [comment]
so what are we doing with this one again? If it's not going in please close it. If it is going on then rebase it.

**Comment by grd** [comment]
I don't think there is anything wrong with it.

**Comment by rminnich** [comment]
You'll need to rebase then.

**Comment by rminnich** [comment]
LGTM

**Pull request merged**
