### PR TITLE
Remove '-mcmodel=small' and '-mno-red-zone' from LIB_COMPILER_FLAGS

### PR DESCRIPTION
**Pull request by dancrossnyc**
Signed-off-by: Dan Cross <cross@gajendra.net>

### CODE REVIEW

**Comment by elbing** [comment]
Derived from days when flags were common for klibs and libs. LGTM

**Comment by elbing** [comment]
LGTM

**Comment by rminnich** [comment]
I'm assuming someone tested this to booting? Please don't merge unless you did.

**Comment by elbing** [comment]
Tested:
image

**Comment by dancrossnyc** [comment]
It has been tested. :-)

**Pull request merged**
