### PR TITLE
Removed unused vars

### PR DESCRIPTION
**Pull request by grd**

### CODE REVIEW

**Comment by elbing** [comment]
This builds ok, but , must be tested in order all keep working. For example, vesa or factotum.
Reviewing.

**Comment by elbing** [comment]
Branch is out of date, please push "Update Branch" button :-)

**Comment by grd** [comment]
Where is the "Update Branch" button?

2016-03-01 11:56 GMT+01:00 Álvaro Jurado <notifications@github.com>:

**Comment by elbing** [comment]
[https://cloud.githubusercontent.com/assets/25792/9596932/82df93f2-5030-11e5-84ec-ea15e16ed887.png](here)

**Comment by elbing** [comment]
LGTM

**Comment by elbing** [comment]
Please push "Update Branch" again in order I could merge this, :-).

**Comment by grd** [comment]
I am still not seeing the "Update Branch" button. Is this something of
github pro?

2016-03-03 10:04 GMT+01:00 Álvaro Jurado <notifications@github.com>:

**Comment by elbing** [comment]
Ok, it can't be done manually, I need to make some mes with git. Later, from my job I can't.

**Comment by grd** [comment]
I can't do this with git in my local repo? I can think of git stach but am not sure how this works with pull requests.

**Comment by grd** [comment]
Now my branch is up to date.

**Comment by sevki** [comment]
hey @grd I'm going to close this pull request and you are going to have to reopen it because this pull requests origin is from the repo you've deleted. So please open a new pull request with this patch

**Pull request closed without merging**
