### PR TITLE
ACPI changes for the next step: running AML in user mode.

### PR DESCRIPTION
**Pull request by rminnich**
This required changes to devacpi,#$, and #P; a new program; and new code.

It's pretty close. It only fails so fair on vmware. Works fine on all hardware I tested.

Don't LGTM without testing first :-)

### CODE REVIEW

**Comment by elbing** [comment]
You will need to update the branch, but make sure it's signed-off after that. Github button doesn't provide the signing.
I'll test on real hardware tonight.

**Comment by elbing** [comment]
Tested, Asus A1M1 AMD Athlon X4. Working.
LGTM

**Comment by elbing** [comment]
Rebase from your branch, if you want to keep the signed-off process.

**Comment by rminnich** [comment]
annoying ... the merge commit is not signed. How do we get rid of merge commits?

**Comment by rminnich** [comment]
oh boy, here we go!

**Pull request merged**
