### PR TITLE
Bringing back console to kernel

### PR DESCRIPTION
**Pull request by elbing**
Round 1

Signed-off-by: Álvaro Jurado <elbingmiss@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
I'm not sure I understand bringing back rdb. We have no use for it. Are you sure you want to do that?

**Comment by elbing** [comment]
get the last commit, PR was updated, rdb is gone. My fault. Also, uart doesn't need to be touched. Now it works and boots. But changing boot.c doesn't.

**Comment by elbing** [comment]
At last status, result is:

init: starting /bin/rc
10.0.2.15# init: rc exit status: rc 425: false

every time. Any clue?

**Comment by rminnich** [comment]
Turn on printallsyscalls in syscall.c and see if rc exits from the read with 0 bytes. That means your console is returning eof.

**Comment by elbing** [comment]
we're closer:

```
init: starting /bin/rc
10.0.2.15# ls -l7
ls��
     -�: bad character in file name: '/bin/ls��
                                                -'
l�G7ǎ: bad character in file name: '/bin/l�G7ǎ'
l���9: '/bin/l���9' does not exist
10.0.2.15# ls -l
�: '/bin/' does not exist
l�s9�: bad character in file name: '/bin/l�s9'
l�: bad character in file name: '/bin/l�'
10.0.2.15# 777777777777777777777777777777777777777777777777777777777777777777777777777777777777
�7777777777777777777777777777777777777777777777777777777777777777777777777777777777778��: bad character in file name: '/bin/�7777777777777777777777777777777777777777777777777777777777777777777777777777777777778�
10.0.2.15# 
�: bad character in file name: '/bin/�'
10.0.2.15# 
�: bad character in file name: '/bin/�'
10.0.2.15# 
�: bad character in file name: '/bin/�'
10.0.2.15# ls -l
�: '/bin/' does not exist
l�s�9: bad character in file name: '/bin/l�s�9'
l�: bad character in file name: '/bin/l�'
10.0.2.15#
```

**Comment by rminnich** [comment]
This is a good time for gdb, or just put some prints in devcons and hexdump the results of qread as you get the data. The kernel has a hexdump function so that's easy. 
n = qread(q, buf, whatever)
hexdump(buf, n)

**Comment by rminnich** [comment]
did you forget to add port/devkbmap.c

**Comment by elbing** [comment]
This last change, after probing many things, really is just cosmetic for being in line with i8042.c.
I tried old putstrn0 and consdevputs and there's no any change about garbage. So Aki's mess is clever than that and better, over all for uart console. Anyway, I included old usartconsole in devuart.c thinking "maybe".

**Comment by elbing** [comment]
My god, I forgot devkbmap.c :-D

**Comment by elbing** [comment]
All working.
Still cat /sys/lib/kbmap/es >/dev/kbmap gives me permission denied, mounted directory. But that's another issue. Next is making work keymaps.

**Pull request merged**
