### PR TITLE
ACPI: fix the issue with merging device IRQs.

### PR DESCRIPTION
**Pull request by rminnich**
There were several little bugs here. I can now
boot with two nics, one at 2:4.0 and one at 2:0.0.

This may also help virtio.

Note this kind is in need of lots of love. The big goal
was to get it to work at all ...

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
This now works on vmware and qemu, please test.

**Comment by dmgolubovsky** [comment]
It seems to resolve the IRQ sharing for virtio.
```
          3           0                    0                    0 trap     #BP
          7           0                    1                 2032 trap     #NM
          8           0                    0                    0 trap     #DF
         14           0                 1265           2271592196 trap     #PF
         15           0                    0                    0 trap     #15
         16           0                    0                    0 trap     #MF
         19           0                    0                    0 trap     #XF
         50          50                25589           4628190911 lapic    APIC timer
         65           1                  270            212120660 ioapic   keyb
         73          12                 2039            634446098 ioapic   mouse
         89          11                 2724           1263992437 ioapic   virtio-balloon-7
         89          11                 2724           1263992437 ioapic   virtio-scsi-4
         89          11                 2724           1263992437 ioapic   virtio-console-3
         89          11                 2724           1263992437 ioapic   virtio-net-0
         89          11                 2724           1263992437 ioapic   ether0
        113          10                    0                    0 ioapic   virtio-rng-6
        113          10                    0                    0 ioapic   virtio-block-5
        113          10                    0                    0 ioapic   virtio-9p-2
        113          10                    0                    0 ioapic   virtio-9p-1
```

It even can share IRQ with other type of devices.

Thanks for fixing it.

**Comment by dmgolubovsky** [comment]
When I am in the pci.c around line 418 (pcicfginit) is there any way to see what interrupt lines are available and their type (per the note in the code I need level not edge)? I might try to distribute these lines across virtio devices evenly to reduce sharing.

**Comment by rminnich** [comment]
Thanks for that picture of IRQs! This is really nice to see. I'm looking forward to having virtio.

**Comment by elbing** [comment]
Real hardware, as you know:

```
192.168.1.128# cat /dev/irqalloc
          3           0                    0                    0 trap     #BP
          7           0                    0                    0 trap     #NM
          8           0                    0                    0 trap     #DF
         14           0                 1144            984695559 trap     #PF
         15           0                    0                    0 trap     #15
         16           0                    0                    0 trap     #MF
         19           0                    0                    0 trap     #XF
         50          50                23813            573216362 lapic    APIC timer
         65           1                    0                    0 ioapic   keyb
         73          12                    0                    0 ioapic   mouse
         81          11                 5927             94099123 msi      ether0
        121          15                    0                    0 msi      sdE (iahci)
```

**Comment by rminnich** [comment]
so, that looks right to me, is it?

**Comment by elbing** [comment]
LGTM

**Pull request merged**
