### PR TITLE
Fixing again ninep building issues ("lionkov").

### PR DESCRIPTION
**Pull request by elbing**
I think this should get master branch by default, --remote flag
and "new commits" detected from Ron's repo.

### CODE REVIEW

**Comment by rminnich** [comment]
Looks find to me assuming it works.

**Comment by elbing** [comment]
Only way to test is cloning repo, applying patch and see if after bootstrap.sh there's a util/ufs.

**Comment by sevki** [comment]
no util/ufs

**Comment by elbing** [comment]
Fuck... any idea? if you go to ninep path and do git branch -a you will see it's not in master branch, an then Ron's changes to fix Go path problem don't work.

**Pull request closed without merging**
