### PR TITLE
build: get rid of sh dependencies

### PR DESCRIPTION
**Pull request by rminnich**
and clean up heinous shell code while we're at it.

Temporarily disable the syscall command. It has obsolete dependencies
on 32-bit ABIs and kenc issues. Someone can fix it someday if they care.

If someone can fix that awful fossil conf.rc mess I'd be grateful.
I'm done for the day.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by elbing** [comment]
Oh man... That's there since early days. I'll try adding it to mksys.

**Comment by rminnich** [comment]
I have this almost working but I'm going to crash now. Kids made me sick.

**Comment by rminnich** [comment]
actually I would not worry about that fossil and venti conf.rc stuff. We want those file systems to go away anyway.

**Comment by elbing** [comment]
I could evaluate how of all of that parsed script is still needed and for what. Though I'm back to apex.
Have fun with kids, grandpa.

**Pull request merged**
